astra_db:
  collection_name: "asistPro"

embedding_model:
  provider: "google"
  model_name: "models/gemini-embedding-001"

retriever:
  top_k: 10

llm:
  provider: "google"
  model_name: "llama-3.1-8b-instant"